apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    app: techtrends
  namespace: {{.Values.namespace.name}}

spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image.repository}}:{{.Values.image.repository}}
        ports:
        - containerPort: {{.Values.containerPort}}
        livenessProbe:
          httpGet:
            path: {{.Values.livenessProbe.path}}
            port: {{.Values.livenessProbe.port}}
        readinessProbe:
          httpGet:
            path: {{.Values.readinessProbe.path}}
            port: {{.Values.readinessProbe.port}}
        resources:
          requests:
            cpu: {{.Values.resources.requests.cpu}}
            memory: {{.Values.resources.requests.memory}}
          limits:
            cpu: {{.Values.resources.limits.cpu}}
            memory: {{.Values.resources.limits.memory}}}}
    