name: TechTrends - Package with Docker
on:
  push:
    branches:
      - 'master'
jobs:
  docker-build-techtrends:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      run: |
        
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Build the Docker image
      run: |
      
        docker build . --file Dockerfile --tag gouda99/my-repo:techtrends-1.0
    - name: Docker push
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/my-repo:techtrends-1.0

